title: Dia Zafrin
url: url: "https://zafrin.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/zafrin"
footer_text: "Built using Ankit Sultana's Researcher Theme"

sass:
    style: compressed
    sass_dir: _sass
